splash = false

wallpaper {
	monitor = DP-1
	path = ~/.config/hypr/wallpapers/main.png
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = ~/.config/hypr/wallpapers/secondary.png
	fit_mode = cover
}

wallpaper {
	monitor = eDP-1
	path = ~/.config/hypr/wallpapers/tertiary.png
	fit_mode = cover
}

wallpaper {
	monitor = 
	path = ~/.config/hypr/wallpapers/tertiary2.png
	fit_mode = cover
}
